# 04 Data Preprocessing dengan Scikit-Learn

## Sample Dataset

In [1]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5], 
                        [-1.5, 2.4, 3.5], 
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

- Terdapat 3 Baris
- Masing - masing baris terdapat 3 features
- Variabel sample_data menampung dataset

In [2]:
sample_data.shape

(4, 3)

(4, 3) artinya terdapat 3 baris dan 4 kolom

## Binarisation

- Untuk menghasilkan suatu data yang terdiri dari 2 numerik saja yaitu 0 dan 1

In [3]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [4]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

- Variabel preprocessor menampung objek binarizer
- Variabel binarised_data menampung hasil tranformasi
- threshold=0.5 artinya setiap nilai yang lebih kecil atau sama dengan 0.5 akan dikonversikan menjadi nilai 0

## Scaling

- Untuk menghasilkan suatu data numerik yang berada dalam rentan skala tertentu

In [5]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [6]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

- Nilai 0 akan mengindikasikan nilai terkecil dari skala yang baru
- Nilai 1 akan mengindikasikan nilai terbesar dari skala yang baru
- Variabel preprocessor untuk menampung objek scaler
- Variabel scaled_data untuk menampung hasil tranformasi
- Tujuan MinMaxScaler yaitu mengubah skala nilai terkecil dan terbesar dari dataset yang dimiliki ke skala tertentu

In [7]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Metod fit_tranform untuk menyatukan proses fiting dan proses tranformasi pada sample yang sama 

## L1 Normalisation: Least Absolute Deviations

- Untuk melakukan normalisasi terhadap data numerik

Referensi: https://en.wikipedia.org/wiki/Least_absolute_deviations

In [8]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [9]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

- preprocessing.normalize membutuhkan 2 parameter
- Parameter pertama yaitu sample_data
- Parameter kedua yaitu norm
- Normalisasi l1 akan berasosiasi dengan normalisasi yang menerapkan least absolute deviations
- Variabel l1_normalised_data untuk menampung data yang sudah dinormalisasi

## L2 Normalisation: Least Squares

Referensi: https://en.wikipedia.org/wiki/Least_squares

In [10]:
sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [11]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

- preprocessing.normalize membutuhkan 2 parameter
- Parameter pertama yaitu sample_data
- Parameter kedua yaitu norm
- Normalisasi l2 akan berasosiasi dengan normalisasi yang menerapkan least squares
- Variabel l2_normalised_data untuk menampung data yang sudah dinormalisasi